# Generated by Django 5.0.1 on 2025-11-14 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('sports', 'Sports')], max_length=20)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=20)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('band', 'Resistance Band'), ('kettlebell', 'Kettlebell'), ('other', 'Other')], max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='How to perform the exercise')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('is_custom', models.BooleanField(default=False, help_text='Created by user vs. system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('average_duration', models.PositiveIntegerField(default=0, help_text='Average duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_routines', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='workouts.workoutroutine')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_reps', models.PositiveIntegerField(default=10)),
                ('default_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Default weight in kg', max_digits=6, null=True)),
                ('default_rest_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutroutine')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, help_text='Total weight lifted in kg', max_digits=10)),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.workoutroutine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('set_type', models.CharField(choices=[('normal', 'Normal'), ('warmup', 'Warm-up'), ('dropset', 'Drop Set'), ('failure', 'To Failure')], default='normal', max_length=20)),
                ('reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('difficulty', models.PositiveIntegerField(blank=True, help_text='Difficulty rating 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('is_personal_record', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['category', 'muscle_group'], name='workouts_ex_categor_67a5cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutlike',
            unique_together={('user', 'routine')},
        ),
        migrations.AlterUniqueTogether(
            name='routineexercise',
            unique_together={('routine', 'order')},
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-start_time'], name='workouts_wo_user_id_d67e38_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseset',
            index=models.Index(fields=['session', 'exercise', 'set_number'], name='workouts_ex_session_0c5003_idx'),
        ),
    ]
