# Generated by Django 5.0.1 on 2025-11-17 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_secondary_muscles_bodyweightlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('shoulders', 'Shoulders'), ('triceps', 'Triceps'), ('biceps', 'Biceps'), ('back', 'Back'), ('forearms', 'Forearms'), ('calves', 'Calves'), ('neck', 'Neck'), ('chest', 'Chest')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
