# Generated by Django 5.0.1 on 2025-12-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercise_secondary_muscles'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='custom_sets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='use_custom_sets',
            field=models.BooleanField(default=False),
        ),
    ]
